#!/usr/bin/env bash
set -euo pipefail
CKPT="${1:?usage: $0 /path/to/zero-checkpoint /path/to/output}"
OUT="${2:?usage: $0 /path/to/zero-checkpoint /path/to/output}"
mkdir -p "$OUT"
if [[ ! -f "$CKPT/zero_to_fp32.py" ]]; then
  echo "zero_to_fp32.py not found under $CKPT" >&2
  echo "Use the zero_to_fp32.py generated by DeepSpeed in the checkpoint directory." >&2
  exit 1
fi
python "$CKPT/zero_to_fp32.py" "$CKPT" "$OUT/pytorch_model.bin"
# Copy tokenizer/config from the original model separately if needed.
echo "Wrote: $OUT/pytorch_model.bin"
